services:
  bus:
    container_name: bus_container
    build: ./bus/
    ports:
      - "1111:80"
    networks:
      - bus_network
    volumes:
      - /bus:/opt/venkatesh_bus
  flight:
    container_name: flight_container
    build: ./flight/
    networks:
      - flight_network
      - bus_network
    ports:
      - "2222:80"
    volumes:
      - /flight:/opt/venkatesh_flight
    env_file: ./srv1.env
      
  movie:
    container_name: movie_container
    networks: 
      - movie_network
    build: ./movie/
    restart: always
    ports:
      - "3333:80"
    volumes:
      - /movie:/opt/venkatesh_movie
    environment:
      name: venkatesh
      place: Eluru
      age: 26
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
        reservations:
          cpus: "0.25"
          memory: 64M


networks:
  bus_network:
    driver: bridge
  movie_network:
    driver: bridge
  flight_network:
    driver: bridge

